version: '3.8'

volumes:
  postgres:
  pgadmin:

services:
  postgres:
    container_name: library_postgres
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: "library"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "superuser"
      PGDATA: "/data/postgres"
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/database:/docker-entrypoint-initdb.d
    restart: unless-stopped

  server:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - postgres.url=jdbc:postgresql://postgres:5432/library
      - postgres.username=superuser
      - postgres.password=secret
      - captcha.secret=
      - mail.username=
      - mail.password=
    depends_on:
      - postgres